name: Django CI

on: [push]

jobs:


  deploy:
    runs-on: ubuntu-latest


    steps:


    - name: Copy project files to server
#      run: |
#        ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}
#        ${{ secrets.CLONE_REPO }}
      run:
        ssh -tt StrictHostKeyChecking=no wioswa@51.250.102.212

      env:
        AWS_EC2_METADATA_DISABLED: true

