name: HomeWork_81

on: [push]

jobs:


  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
#        ssh-private-key: ${{ secrets.SSH_KEY }}
        ssh-private-key: b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACBwkw7JpuVHx+UBXjRNth952lrShC4cGwSEt6vYx+454QAAAJjhdF6d4XRe
nQAAAAtzc2gtZWQyNTUxOQAAACBwkw7JpuVHx+UBXjRNth952lrShC4cGwSEt6vYx+454Q
AAAEBEJ/6FrjmLsUgyy3/v7RAxJTpbgBXUgYmkuuCAHY9kjnCTDsmm5UfH5QFeNE22H3na
WtKELhwbBIS3q9jH7jnhAAAADmFrdmFAQ2hpa2FDb21wAQIDBAUGBw==


    - name: Add SSH host key
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Join to server
      run: ssh -T -o StrictHostKeyChecking=no wioswa@89.169.174.227