name: Django CI

on: [push]

jobs:


  deploy:
    runs-on: ubuntu-latest


    steps:
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}


#
    - name: Add SSH host key
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Join to server
#      run: |
#        ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}
#        ${{ secrets.CLONE_REPO }}
      run:
#        ssh -t -t StrictHostKeyChecking=yes wioswa@51.250.102.212
        ssh -T -o StrictHostKeyChecking=no wioswa@51.250.99.186

#      env:
#        AWS_EC2_METADATA_DISABLED: true


#  deploy:
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Set up SSH
#        run: |
#          sudo apt-get install -y sshpass  # Установка sshpass
#          echo "${{ secrets.SSH_PASSWORD }}" > password.txt  # Сохранение пароля во временный файл
#          chmod 600 password.txt  # Установка прав доступа к файлу
#
#      - name: Add SSH host key
#        run: |
#          mkdir -p ~/.ssh
#          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
#
#      - name: Copy project files to server
#        run: |
#          sshpass -f password.txt rsync -avz --exclude '__pycache__' . ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}
#
#      - name: Deploy to Server
#        run: |
#          sshpass -f password.txt ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
#          cd ~
#          git clone https://github.com/kashina161197/coursework_5.git
#          cd coursework_5
#          docker system prune -af
#          docker volume prune -f
#          docker-compose up -d --build
#          EOF